[package]
name = "gupax"
version = "0.1.0"
edition = "2021"

[dependencies]
egui = "0.19.0"
eframe = "0.19.0"
egui_extras = { version = "0.19.0", features = ["image"] }
image = { version = "0.24.4", features = ["png"] }
num_cpus = "1.13.1"
monero = "0.18.0"
regex = "1.6.0"
log = "0.4.17"
env_logger = "0.9.1"
chrono = "0.4.22"

[profile.optimized]
inherits = "release"
strip = "debuginfo"
debug = false
debug-assertions = false
lto = true
overflow-checks = false
incremental = true
codegen-units = 1
rpath = false

[profile.optimized.package."*"]
opt-level = 3
