[toolchain]
channel = "nightly-2024-04-08"
components = [ "rustfmt", "rustc-dev", "cargo", "clippy", "rust-analyzer"]
target = ["x86_64-unknown-linux-gnu", "aarch64-apple-darwin", "x86_64-apple-darwin","x86_64-pc-windows-gnu"]
