[toolchain]
channel = "nightly-2024-03-21"
components = [ "rustfmt", "rustc-dev", "cargo", "clippy", "rustc-codegen-cranelift-preview", "rust-analyzer"]
target = ["x86_64-unknown-linux-gnu", "aarch64-apple-darwin", "x86_64-pc-windows-gnu"]
