name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: "full"

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-2019, macos-11, ubuntu-20.04]
        build: [dev, release]

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo
          target
        key: ${{ matrix.os }}-${{ matrix.build }}

    - name: Install dependencies
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          sudo apt update
          sudo apt install -y libgtk-3-dev
        elif [ "$RUNNER_OS" == "macOS" ]; then
          cargo install cargo-bundle
          rustup target install aarch64-apple-darwin
        fi
      shell: bash

    - name: Test
      run: cargo test --all-features --profile ${{ matrix.build }}

    - name: Build
      run: |
        if [ "$RUNNER_OS" == "macOS" ]; then
          cargo bundle --all-features --profile ${{ matrix.build }}
          cargo bundle --all-features --profile ${{ matrix.build }} --target aarch64-apple-darwin
        else
          cargo build --all-features --profile ${{ matrix.build }}
        fi
      shell: bash

    - name: Archive
      uses: actions/upload-artifact@v3
      with:
        name: festival-${{ matrix.os }}
        path: target
