name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: "full"

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-2019, macos-11, ubuntu-20.04]

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo
          target
        key: ${{ matrix.os }}

    - name: Install dependencies
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          sudo apt update
          sudo apt install -y libgtk-3-dev
        elif [ "$RUNNER_OS" == "macOS" ]; then
          cargo install cargo-bundle
          rustup target install aarch64-apple-darwin
        fi
      shell: bash

    - name: Test
      run: cargo test --all-features --release

    - name: Build
      run: |
        if [ "$RUNNER_OS" == "macOS" ]; then
          cargo bundle --all-features --release
          cargo bundle --all-features --release --target aarch64-apple-darwin
          chmod +x target/release/bundle/osx/Gupax.app/Contents/MacOS/gupax
          chmod +x target/aarch64-apple-darwin/release/bundle/osx/Gupax.app/Contents/MacOS/gupax
        elif [ "$RUNNER_OS" == "Linux" ]; then
          cargo build --all-features --release --target x86_64-unknown-linux-gnu
        else
          cargo build --all-features --release
        fi
      shell: bash

    - name: Archive (Windows)
      if: ${{ runner.os == 'Windows' }}
      uses: actions/upload-artifact@v3
      with:
        name: windows
        path: target/release/gupax.exe

    - name: Archive (macOS-x64)
      if: ${{ runner.os == 'macOS' }}
      uses: actions/upload-artifact@v3
      with:
        name: macos-x64
        path: target/release/bundle/osx/Gupax.app

    - name: Archive (macOS-arm64)
      if: ${{ runner.os == 'macOS' }}
      uses: actions/upload-artifact@v3
      with:
        name: macos-arm64
        path: target/aarch64-apple-darwin/release/bundle/osx/Gupax.app

    - name: Archive (Linux)
      if: ${{ runner.os == 'Linux' }}
      uses: actions/upload-artifact@v3
      with:
        name: linux
        path: target/x86_64-unknown-linux-gnu/release/gupax
