name: Linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Cache
      uses: actions/cache@v3.2.3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: linux
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y libgtk-3-dev
    - name: Build
      run: cargo build
    - name: Test
      run: cargo test
