name: macOS Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Cache
      uses: actions/cache@v3.2.3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: macos cargo test
    - uses: actions/checkout@v3
    - name: Test
      run: cargo test
